---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Adjust based on how much video history you want to keep
